name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Lệnh này bảo robot: "Hãy chú ý các file lớn"

      - name: Install Git LFS
        run: git lfs install # Kích hoạt trình quản lý file lớn

      - name: Fetch LFS objects
        run: git lfs pull # Lệnh then chốt: Tải dữ liệu thật của file .safetensors về máy ảo

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Xóa cấu hình cũ nếu có để tránh lỗi 'remote hf already exists'
          git remote remove hf || true 
          git remote add hf https://Jadewave:$HF_TOKEN@huggingface.co/spaces/Jadewave/trans
          # Đẩy kèm theo cờ --all để đảm bảo LFS cũng được đẩy đi
          git push --force hf main
